version: "3.9"
services:
  db:
    image: mysql
    ports:
      - '3307:3307'
    expose:
      - '3307'
    command: bash -c "mysqld --initialize --user=root"
    environment:
      - MYSQL_USER= root
    volumes:
      - chat.development.mysql2:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    expose:
      - '6379'
    volumes: 
      - cache:/data
  web:
    build: .
    command: bash -c "gem install bundler && bundle update && bundle exec rails db:create && rails db:migrate RAILS_ENV=development && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chat-system-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    environment:
      - REDIS_URL_CACHING=redis://cache:6379/0
volumes:
  chat.development.mysql2:
  cache:
